### ISSUE TITLE
cannot generate dependency graph for a clojurescript project that has npm dependency

### ISSUE THREAD

**Issue by viebel** [greglook/clj-hiera#5]
In clojurescript,  one can require npm modules using the following syntax:

```
(:require ["honeybadger-js" :as honeybadger])
```

The npm module to required is passed as a string.
See [here](https://clojurescript.org/news/2017-07-12-clojurescript-is-not-an-island-integrating-node-modules) for the full details.

hiera doesn't handle this case properly:

See the error below:
```bash
$ lein hiera
java.lang.IllegalArgumentException: "Unparsable namespace form:" ["honeybadger-js" :as honeybadger]
 at clojure.tools.namespace.parse$deps_from_libspec.invokeStatic (parse.clj:78)
```

**Comment by greglook** [comment]
This looks like an issue with `clojure.tools.namespace`, which is the library that `lein-hiera` uses to build the dependency graph. If a newer version has been released which works with this style of requires then upgrading should fix the issue. You should be able to try that by adding an explicit dependency in your leiningen plugins vector.

**Comment by viebel** [comment]
Unfortunately, `clojure.tools.namespace` doesn't support this case at the moment.
I have opened a bug https://dev.clojure.org/jira/browse/TNS-51

Can you think of a workaround?

**Comment by greglook** [comment]
I believe this is no longer an issue, but let me know if you still have troubles here.
