### ISSUE TITLE
:ignore-ns not working

### ISSUE THREAD

**Issue by klauswuestefeld** [greglook/clj-hiera#7]
Hi, none of these work calling hiera from a shell script:
lein hiera :show-external true :ignore-ns #{clojure}
lein hiera :show-external true :ignore-ns \\#{clojure}
lein hiera :show-external true :ignore-ns "#{clojure}"

The image gets generated but clojure.* namespaces are still shown.

**Comment by klauswuestefeld** [comment]
In the first case, everything after # is ignored as a comment, of course.

**Comment by and-z** [comment]
Hi, @klauswuestefeld 

this library conjoins the value of the `:ignore-ns` CLI argument into a set. The docstring states also clearly:

> [...] May be provided multiple times.

You could exclude e.g. both `clojure` and `dev` namespaces like this:
`lein hiera :show-external true :ignore-ns clojure :ignore-ns dev`

Cheers
Andreas

**Comment by klauswuestefeld** [comment]
What docstring?

The readme file is misleading: "A set of namespace prefixes to exclude from the graph. For example, #{clojure} would exclude clojure.string, clojure.java.io, etc."

**Comment by and-z** [comment]
Hi @klauswuestefeld ,
you're right. The readme describes imho not the CLI option but the implementation detail.

The [docstring](https://github.com/greglook/lein-hiera/blob/5ac399d3c7e8bdec862ba7a847b3b4918b6fe58b/src/leiningen/hiera.clj#L161) of the Leiningen Plugin `hiera` function describes the expected parameter.

Cheers,
Andreas

**Comment by greglook** [comment]
In the 2.0.0 version, `:ignore` is a set which may contain symbol prefixes or regex patterns. Since it's using kwarg-style arguments to build the map, passing in an explicit set is the correct approach now.
